	PROGRAM CERN
        IMPLICIT DOUBLE PRECISION (A-H,O-Z)
 	COMMON /SEED/ISEED
	call futil
 	ISEED=-1
        write (*,100)
100     format (' DOUBLE PRECISION MINUIT')
C
C	Open Files
C
	OPEN (UNIT=5,FILE='MINRD.DAT')
	REWIND 5
	OPEN (UNIT=6,FILE='MINWR2.DAT')
	REWIND 6
	OPEN (UNIT=7,FILE='MINPU2.DAT')
	REWIND 7
C
 	CALL MINUIT
 	STOP
 	END
