C      PROGRAM FOR HISTOGRAM REBINNING GENERAL ROUTINE
C       EISAGWGIKA STOIXEIA, METABLHTES K.L.P. 
       REAL*8 EXPER,MCNP,ENERGEIA,O,P,MODULO1
       INTEGER DIV,L,CHANNEL,N,ORIO
       REAL*8 MODULO,FULL,SUMMY(2100),SUMM(2100),NEWOLOK
       REAL*8 ENERGY(3000),BINCON(3000),BINTHEO(3000)
       REAL*8 BINMCNP,BINEXP,BINOFF,EN(3000),OLOKLIR
       REAL*8 YIELD(2100),NEWOLOK1
       CHARACTER*50 FILENAM1,FILENAM2
       WRITE(*,*)'PLEASE GIVE ME THE NAME OF THE INPUT FILE'
       READ(*,2)FILENAM1
       WRITE(*,*)'PLEASE GIVE ME THE NAME FOR THE OUTPUT REBINNED FILE'
       READ(*,2)FILENAM2
 2     FORMAT(A50)
       WRITE(*,*)'NOW I WANT THE keV/ch EXPERIMENTAL PARAMETER'
 12    READ(*,*)BINEXP
        IF(BINEXP.LE.0.OR.BINEXP.LT.1.)THEN
        WRITE(*,*)'THAT IS CRAP...TRY AGAIN!'
        GOTO 12
        ENDIF
       WRITE(*,*)'...AND THE OFFSET PLEASE (IN keV)'
       READ(*,*)BINOFF
C       EDW DIABAZEI TO ARXEIO EISODOY...
C       YPOLOGIZEI KAI TO OLOKLHRWMA AYTOY
       OPEN(UNIT=25, FILE=FILENAM1, STATUS='OLD')
       DO I=1,2800
       READ(25,*)ENERGY(I),BINCON(I),BINTHEO(I)
       EN(I)=ENERGY(I)*1000
       OLOKLIR=OLOKLIR+BINCON(I)
 25    END DO
       WRITE(*,*)'TO OLOKLHRWMA TOY ARXIKOY FASMATOS EINAI:',OLOKLIR
       CLOSE(25)
C       EDW ARXIZEI H KYRIA DOYLEIA, DHLADH TO REBINNING ME YPOLOGISMO
C       OLOKLHRWMATWN
       BINMCNP=EN(2)-EN(1)
       DIV=0
       NEWOLOK=0.
       FULL=0.
       MODULO=0.
       REST=0.
C      H METABLHTH 'EXPER' EINAI STHN PRAGMATIKOTHTA 'WIDTH FACTOR'
C      KAI ETSI MPOROUME NA KANOYME ME MATHIMATIKH ASFALEIA OPOIADHPOTE
C      SYMPIESH...GIA DIEYRYNSH THA DOYLEPSEI, ALLA ME ASAFEIES...
       EXPER=BINEXP/BINMCNP
       MCNP=BINMCNP
       DO 47, I=1,2100
         SUMM(I)=0.
         SUMMY(I)=0.
         YIELD(I)=0.
 47    ENDDO
       CHANNEL=2800/EXPER+1
	     ORIO = 1024
Ccccccccccc   Paremvasi Geo ..den xero an doulepsei theto orio kateftheian 1024
C        IF(CHANNEL.GT.1022)THEN
C         ORIO=2047
C         ELSE
C         ORIO=1023
C        ENDIF
		 
       OPEN(UNIT=35,FILE=FILENAM2,STATUS='UNKNOWN')
C       AYTOS EINAI O BASIKOS YPOLOGISMOS 
       DO 55, K=1,CHANNEL
        DIV=INT(K*EXPER)
        FULL=K*EXPER
        MODULO=FULL-DIV
        DO 45, I=1,DIV
        SUMM(K)=SUMM(K)+BINCON(I)
 45     END DO
       SUMM(K)=SUMM(K)+MODULO*BINCON(1+DIV)
       DIV1=INT((K+1)*EXPER)
       FULL1=(K+1)*EXPER
       MODULO1=FULL1-DIV1
        DO 46, I=1,DIV1
        SUMMY(K)=SUMMY(K)+BINCON(I)
 46     END DO
        SUMMY(K)=SUMMY(K)+MODULO1*BINCON(1+DIV1)
        IF(K.EQ.1)THEN
         YIELD(K)=SUMM(K)
        ENDIF
        YIELD(K)=SUMMY(K)-SUMM(K)
       NEWOLOK=NEWOLOK+YIELD(K)
 55    ENDDO 
C       EDW OLOKLHRWNETAI H DIADIKASIA TOY REBINNING ME GRAPSIMO
C       STO ARXEIO EKSODOY TWN: KANALI, ENERGEIA, PERIEXOMENO
C       (TRISTHLO DHLADH)
       DIV=INT(EXPER)
       FULL=EXPER
       MODULO1=FULL-DIV
Ccccccc Kai edo allagi Geo....opou to 1024 einai CHANEL
       DO 86, K=1,1024
        ENERGEIA=K*BINEXP+BINOFF
        N=INT(BINOFF/BINEXP)
        O=BINOFF/BINEXP
        P=ABS(O-N)
         IF(MODULO1.LE.0.5.AND.P.LE.0.5)THEN
          WRITE(35,*)K,ENERGEIA,YIELD(K+N-1)
         ENDIF
         IF(N.GT.0.AND.P.GT.0.5)THEN
          WRITE(35,*)K,ENERGEIA,YIELD(K+N-1)
         ENDIF
          IF(N.LE.0.AND.P.GT.0.5)THEN
          WRITE(35,*)K,ENERGEIA,YIELD(K+N-2)
         ENDIF
	  IF(N.LE.0.AND.P.LE.0.5)THEN
          WRITE(35,*)K,ENERGEIA,YIELD(K+N-1)
         ENDIF
 86    ENDDO
       DO 65, K=CHANNEL+1,ORIO
       ENERGEIA=K*BINEXP+BINOFF
       N=INT(BINOFF/BINEXP)
       O=BINOFF/BINEXP
        P=ABS(O-N)
         IF(P.LE.0.5)THEN
          WRITE(35,*)K,ENERGEIA,YIELD(K+N-1)
         ENDIF
         IF(N.GT.0.AND.P.GT.0.5)THEN
          WRITE(35,*)K,ENERGEIA,YIELD(K+N-1)
         ENDIF
          IF(N.LE.0.AND.P.GT.0.5)THEN
          WRITE(35,*)K,ENERGEIA,YIELD(K+N-2)
         ENDIF
 65    ENDDO      
       CLOSE(35)
C      TELIKO OLOKLHRWMA 'ELEGXOY' KATA KAPOIO TROPO...
       WRITE(*,*)'TO NEO OLOKLHRWMA EINAI',NEWOLOK
       STOP
       END






       

       
